# Match the IDF version the crate set is pinned against (esp-idf-hal 0.45 /
# esp-idf-svc 0.51 / esp-idf-sys 0.36 are the official 5.3 line).
FROM espressif/idf:v5.3.5 AS build
ENV IDF_PATH=/opt/esp/idf
ENV IDF_TOOLS_PATH=/opt/esp
ENV ESP_IDF_TOOLS_INSTALL_DIR=fromenv
ENV PATH=/root/.cargo/bin:${PATH}
RUN bash -o pipefail -c "curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal"
RUN cargo install espup --locked && \
    espup install --toolchain-version 1.90.0.0 --targets esp32 --std && \
    rustup default esp
RUN cargo install ldproxy --locked
WORKDIR /app

# Cache layer: compile all dependencies once against a stub crate. This RUN only
# re-executes when the manifest/toolchain layers change, so CI rebuilds reuse
# the compiled dependencies from the GHA docker layer cache instead of
# recompiling the whole tree on every push.
COPY .cargo/. ./.cargo/
COPY Cargo.toml Cargo.lock build.rs rust-toolchain.toml sdkconfig.defaults partitions.csv ./
RUN mkdir -p src && : > src/lib.rs && : > src/main.rs
# export-esp.sh (generated by espup) sets LIBCLANG_PATH to the Espressif
# Xtensa-enabled libclang inside the esp toolchain; bindgen needs that clang to
# parse the ESP-IDF headers, a stock libclang cannot handle the 'xtensa' target.
RUN bash -c "source \$HOME/export-esp.sh && source \$IDF_PATH/export.sh && cargo build --release --lib"

# The real sources (lib.rs above is overwritten here); only this crate's own
# code recompiles from this layer on. espup bundles clippy; it is already
# present in the toolchain. The firmware size budget is enforced separately in
# CI via scripts/check-size.ts.
COPY . .
RUN bash -c "source \$HOME/export-esp.sh && source \$IDF_PATH/export.sh && cargo build --release && cargo clippy --release -- -D warnings"
FROM scratch AS release
COPY --from=build /app/target/xtensa-esp32-espidf/release/esp32-gate-opener /esp32-gate-opener
